### ISSUE TITLE
TS2345: Argument of type '{ imports: DynamicModule[]; exports: (typeof ConfigService)[]; 

### ISSUE THREAD

**Issue by jamesliauw** [kyknow/nestjs-redis#10]
TS2345: Argument of type '{ imports: DynamicModule[]; exports: (typeof ConfigService)[]; controllers: (typeof ConfigControl...' is not assignable to parameter of type 'ModuleMetadata'.
  Types of property 'imports' are incompatible.
    Type 'DynamicModule[]' is not assignable to type '(Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>)[]'.
      Type 'DynamicModule' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.
        Type 'DynamicModule' is not assignable to type 'ForwardReference<any>'.
          Property 'forwardRef' is missing in type 'DynamicModule'.

 13 @Module({
            ~
 14  imports: [

my code:
@Global()
@Module({
	imports: [
		RedisModule.forRootAsync({
			useFactory: (configService: ConfigService) => configService.getRedisConfig(),
			inject: [ConfigService]
		})
	],
	exports: [ConfigService],
	controllers: [ConfigController],
	providers: [
		ConfigService,
		{
			provide: DefaultConfig,
			useValue: new DefaultConfig(), // 默认只使用值
		},
	],
})
export class ConfigModule {
...
}

**Comment by skunight** [comment]
你可以参考README.md的示例
