### ISSUE TITLE
can't resolve dependencies of the RedisService

### ISSUE THREAD

**Issue by lichnow** [kyknow/nestjs-redis#16]
'Nest can't resolve dependencies of the MyService (?). Please make sure that the argument at index [0] is available in the CommonModule context. '

**Comment by michaelbats** [comment]
@skunight @lichnow what were you doing wrong? I'm doing it too.

**Comment by AkatQuas** [comment]
How can I use the redis instance in sub-module when the `RedisModule` is registered in `AppModule` ?

**Comment by michaelbats** [comment]
@AkatQuas  you have to register it in both afaik.
