### ISSUE TITLE
Demo or example

### ISSUE THREAD

**Issue by reyco1** [kyknow/nestjs-redis#2]
Is there a demo or example on how I can use this in my project? What is ConfigService? What are the dependencies? Should I have 'ioredis' already installed?

**Comment by skunight** [comment]
> Is there a demo or example on how I can use this in my project? What is ConfigService? What are the dependencies? Should I have 'ioredis' already installed?

ConfigService is a service which can be intject.
You can use like [this](https://github.com/nestjs-community/nestjs-config)
And you don't need install 'ioredis'.
