### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by iamolegga** [kyknow/nestjs-redis#29]
This is popular library, but I see, that some of PRs are not merged, but seems to be ready (one of them is mine). Also I think that I could invest my time in covering this lib with tests, but I'm not sure if it has any sense if it will not be merged

**Comment by trymoto** [comment]
i would help with tests

**Comment by skunight** [comment]
sorry, answered to late, PR is merged

**Comment by iamolegga** [comment]
Thanks, @skunight 👍
