### ISSUE TITLE
is not assignable to parameter of type 'RedisModuleOptions | RedisModuleOptions[]'.

### ISSUE THREAD

**Issue by sinoon** [kyknow/nestjs-redis#3]
Thanks for your work first of all.

When I add config, got error below:

Error:(22, 7) TS2345: Argument of type '{ name: string; host: string; port: number; db: number; password: string; keyPrefix: string; }' is not assignable to parameter of type 'RedisModuleOptions | RedisModuleOptions[]'.
  Object literal may only specify known properties, and 'host' does not exist in type 'RedisModuleOptions | RedisModuleOptions[]'.

![image](https://user-images.githubusercontent.com/6065488/50375041-51ae0000-0632-11e9-853f-4a029e4b1886.png)

Is look like lack of definition, is only name defined
![image](https://user-images.githubusercontent.com/6065488/50375061-afdae300-0632-11e9-8840-5d322bb3c311.png)

**Comment by Charul090** [comment]
Facing same issue, not able to resolve as well !

**Comment by xlxr** [comment]
Anyone know the reason?
